name: Dart

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.3'
          channel: 'stable'
      - run: flutter --version

      - name: Analyze project source
        id: analyze
        run: flutter analyze --no-pub > analyze.txt
        working-directory: ./client
        continue-on-error: true

      - name: Read Comment Text from File
        id: vars
        if: steps.analyze.outcome != 'success'
        working-directory: ./client
        run: |
          echo 'analyze<<EOF' >> $GITHUB_OUTPUT
          cat analyze.txt >> $GITHUB_OUTPUT   
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Post Comment
        uses: actions/github-script@v5
        if: steps.analyze.outcome != 'success'
        with:
          working-directory: ./client
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `${{ steps.vars.outputs.analyze }}`,
            });