name: Spell Check Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  spell-check:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install cspell
      run: npm install -g cspell

    - name: Spell check
      run: cspell **/*.dart --reporter @cspell/cspell-json-reporter > cspell_report.txt
      continue-on-error: true
    
    - name: Read Comment Text from File
      id: comment
      run: |
        echo "comment<<EOF$( cat cspell_report.txt )EOF" >> "$GITHUB_OUTPUT"

    - name: Read Comment Text
      run: |
        echo ${{ steps.vars.outputs.comment }}

    - name: Post Comment
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `${{ steps.vars.outputs.comment }}`,
          });

    # - name: report cspell
    #   uses: dorny/test-reporter@v1
    #   with:
    #     name: 'flutter cspell'
    #     path: 'test_report.log'
    #     reporter: 'flutter-json'
    #     fail-on-error: 'false'
