name: Spell Check Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  spell-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.2.2

    - name: Install codespell
      run: pip install codespell

    - name: Spell check
      run: codespell **/*.dart --skip="*.g.dart"

    - name: Spell check results
      run: cat codespell_results.txt

    - name: report test
        uses: dorny/test-reporter@v1
        with:
          name: 'flutter test'
          path: 'codespell_results.txt'
          reporter: 'flutter-json'
          fail-on-error: 'false'