name: Spell Check Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  spell-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install cspell
      run: npm install -g cspell

    - name: Spell check
      run: cspell **/*.dart > cspell_report.log
      continue-on-error: true

    - name: Upload Text File Artifact
      uses: actions/upload-artifact@v2
      with:
        name: cspell
        path: cspell_report.log

    # - name: report cspell
    #   uses: dorny/test-reporter@v1
    #   with:
    #     name: 'flutter cspell'
    #     path: 'test_report.log'
    #     reporter: 'flutter-json'
    #     fail-on-error: 'false'
